version: '3.8'

services:
  tweetdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: tweetdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./database/dev.sql:/docker-entrypoint-initdb.d/dev.sql

  sessions:
    image: redis:latest
    ports:
      - "6379:6379"